version: "3.8"

# uffizzi integration
x-uffizzi:
  ingress:
    service: mindsdb
    port: 47334

services:

  postgres:
   image: postgres
   environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=iris
     - PGDATA=/tmp
   volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./uffizzi-db-script/:/docker-entrypoint-initdb.d/
   deploy:
            resources:
              limits:
                memory: 500M


  mindsdb:
    image: mindsdb/mindsdb:latest
    #container_name: mindsdb
    volumes:
       # - type: bind
         - source: ./
           target: /mindsdb
    #restart: "always"
    ports:
      - "47334:47334"
      # - "47335:47335"
    # command: bash -c "cd /mindsdb && python -m mindsdb"
    environment:
      MINDSDB_DOCKER_ENV: "True"
      MINDSDB_STORAGE_DIR: "/mindsdb/var"
      FLASK_DEBUG: "1"
      FLASK_ENV: "development"
      FLASK_APP: "/mindsdb/mindsdb/__main__.py"
    # healthcheck:
    #   test:  ["CMD", "curl", "-f", "http://localhost:47334/api/util/ping"]
    #   interval: 30s
    #   timeout: 4s
    #   retries: 100
    deploy:
            resources:
              limits:
                memory: 4000M

  # mindsdb:
  #   image: mindsdb/mindsdb:latest
  #   # volumes:
  #   #   - minds_volume:/root
  #   volumes:
  #       - type: bind
  #         source: ../
  #         target: /mindsdb
    # environment:
    #     MINDSDB_STORAGE_DIR: "/mindsdb/var"
    #     MINDSDB_DOCKER_ENV: "True"
    #     FLASK_DEBUG: "1"
    #     FLASK_ENV: "development"
    #     FLASK_APP: "./mindsdb/__main__.py"


volumes:
  postgres_data:

